/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listaairport_201602909;

/**
 *
 * @author edgom
 */
public class DatosSim_201602909 extends javax.swing.JFrame {

    public static int NoAviones;
    public static int NoER;
    public static int NoEM;
    
    
    public DatosSim_201602909() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noaviones = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        noescritoriosregistro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        noestacioesmantenimiento = new javax.swing.JTextField();
        btmsim = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setTitle("ListaAIRPORT-Datos_Simulacion");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingreso de Datos para la Simulacion");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(204, 58, 387, 27);

        jLabel2.setFont(new java.awt.Font("Colonna MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aviones Entrantes:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(81, 152, 242, 20);
        getContentPane().add(noaviones);
        noaviones.setBounds(81, 178, 320, 19);

        jLabel3.setFont(new java.awt.Font("Colonna MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Escritorios de Registro Disponibles: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(81, 235, 272, 20);
        getContentPane().add(noescritoriosregistro);
        noescritoriosregistro.setBounds(81, 261, 320, 19);

        jLabel4.setFont(new java.awt.Font("Colonna MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estaciones de Mantenimiento Disponibles: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(81, 325, 320, 20);
        getContentPane().add(noestacioesmantenimiento);
        noestacioesmantenimiento.setBounds(81, 357, 320, 19);

        btmsim.setBackground(new java.awt.Color(255, 255, 255));
        btmsim.setForeground(new java.awt.Color(0, 0, 0));
        btmsim.setText("Iniciar Simulacion");
        btmsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmsimActionPerformed(evt);
            }
        });
        getContentPane().add(btmsim);
        btmsim.setBounds(348, 465, 150, 39);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listaairport_201602909/imagenes/DSC_0194.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmsimActionPerformed
    NoAviones = Integer.parseInt(noaviones.getText());
    NoER = Integer.parseInt(noescritoriosregistro.getText());
    NoEM = Integer.parseInt(noestacioesmantenimiento.getText());
    Simulacion_201602909 sim = new Simulacion_201602909();
    sim.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btmsimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosSim_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosSim_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosSim_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosSim_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DatosSim_201602909().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmsim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField noaviones;
    private javax.swing.JTextField noescritoriosregistro;
    private javax.swing.JTextField noestacioesmantenimiento;
    // End of variables declaration//GEN-END:variables
}
